from config.settings import AGENT_ROOT, DATA_DIR, OUTPUTS_DIR, LOG_DIR

DATA_PATH = AGENT_ROOT / DATA_DIR
PROMPTS_DIR = AGENT_ROOT / "prompts"
OUTPUTS_PATH = AGENT_ROOT / OUTPUTS_DIR
DOCUMENTOS_RECIBIDOS_DIR = OUTPUTS_PATH / "documentos_recibidos"
LOGS_PATH = AGENT_ROOT / LOG_DIR

for ruta in [DATA_PATH, PROMPTS_DIR, OUTPUTS_PATH, DOCUMENTOS_RECIBIDOS_DIR, LOGS_PATH]:
    ruta.mkdir(parents=True, exist_ok=True)
